apiVersion: apps/v1
kind: Deployment
metadata:
  name: cashvista-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # Replace 'your-namespace' with the one assigned by your college
        image: nexus.imcc.com/repository/cashvista-backend:v1 
        ports:
        - containerPort: 8000
        env:
# REPLACE THESE VALUES with the actual ones from your college admin
        - name: POSTGRES_SERVER
          value: "postgres-cluster-main-1.cnpg-system.svc.cluster.local" 
        - name: POSTGRES_USER
          value: "mahendradangi"
        - name: POSTGRES_PASSWORD
          value: "mahendra123"
        - name: POSTGRES_DB
          value: "cashvista"  