apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cashvista-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: cashvista.imcc.com # Replace with the URL your college provides
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: cashvista-backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cashvista-frontend
            port:
              number: 80