apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cashvista-ingress
  # REPLACE WITH YOUR NAMESPACE
  namespace: "2401037"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    # REPLACE WITH YOUR DOMAIN (e.g., your-roll-no.imcc.com)
    - host: 2401037.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cashvista-service
                port:
                  number: 80