apiVersion: v1
kind: Service
metadata:
  name: cashvista-service
  # REPLACE WITH YOUR NAMESPACE
  namespace: "2401037"
spec:
  selector:
    app: cashvista
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP